postLink: ${name}
postFileName: ${name}.html
markdownRenderer: ../markdownRenderer
title: Ad:a
author:
  name: Adrian Heine
  uri: https://adrianlang.de/id
baseUrl: https://ada.adrianheine.de
# Since this is used for the feed id, which should never change, you should
# not change this either
atomIdBase: https://ada.adrianlang.de
